## Question1
#Write a function so that the columns of the output matrix are powers of the input vector.  #The order of the powers is determined by the increasing boolean argument.Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 

In [55]:
# import numpy 
import numpy as np

#Function takes an array as input
def matrix_power(in_array):
    
# Find length of the array
    N = len(in_array)

# Create an empty output array
    out_array=np.array([])

# Loop in through the array to calculate the power of the number
    for a in in_array:
        for i in range(N-1,-1,-1):
            out_array= np.append(out_array,[a**i])
            
# Convert from float to int
            out_array = out_array.astype('int64')
  
# Reshape array into N,N
    print(np.reshape(out_array,(N,N)))
            

In [56]:
matrix_power([1,2,3,4,5,6])

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


## Question2: 
Write a function to find moving average in an array over a window:          
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [57]:
# Function takes an array and size as input
def moving_average(in_array,win_int):
# Find length of the array
    N = len(in_array)

# Find how many values will be there in moving average
    N2 = N-win_int+1

# Create an empty array
    out_array = np.array([])

# Loop through the array N2 times and calculate the moving average
    for k in range(0,N2):    
        out_array=np.append(out_array,sum(in_array[k:k+win_int])/win_int)

# Print output
    print(out_array)
    

In [52]:
moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [53]:
moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],4)

[  4.25   5.5    6.75   7.75  23.5   39.5   57.25  79.25  88.   107.5 ]
